version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bot/src:/app/src
      - ./bot/migrations:/app/migrations
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - BOT_PORT=${BOT_PORT}

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
