AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deployment of Exam Question Generator API using AWS SAM.

Globals:
  Function:
    Timeout: 30

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: main.handler
      Runtime: python3.12
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        NonRoot:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY     
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for App function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"